# Generated by Django 3.1.3 on 2020-11-26 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201126_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 19, 25, 30, 362943)),
        ),
    ]
