# Generated by Django 3.1.3 on 2020-11-26 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201126_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 19, 43, 27, 782032)),
        ),
    ]
