# Generated by Django 3.1.3 on 2020-11-26 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201126_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reference_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 21, 49, 26, 199771)),
        ),
    ]
