# Generated by Django 3.1.3 on 2020-11-29 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201129_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 1, 34, 27, 620747)),
        ),
    ]
