# Generated by Django 3.1.3 on 2020-11-29 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201130_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_img',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 1, 48, 34, 118571)),
        ),
    ]
