# Generated by Django 3.1.3 on 2020-11-30 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201130_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 18, 25, 38, 217365)),
        ),
    ]
